[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.26"
via_ir = true
ffi = false

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

[fuzz]
runs = 256
max_test_rejects = 65536

[invariant]
runs = 64
depth = 32
fail_on_revert = false
